import { MaterialIcon } from "../enums/MaterialIcon";
import { CanopyCellData } from "./canopy-data.model";
import { CanopyCell, ImageCard, ListCard } from "./canopy-cell.model";


export class ExampleCanopyDataEntries {
  static dexEntries: CanopyCellData[] = [
    new CanopyCellData( 0,   'Mining Truck',        '',   '',   [new CanopyCell( 0, 'Unit Traits', 'Shard Collector'), new ListCard( 1, 'Abilities', '', ['Shard Resistant', 'Power Shock'])], [new ImageCard( 0, `${MaterialIcon.Image}`)]),
    new CanopyCellData( 1,   'Auto Turret',         '',   '',   [new CanopyCell( 0, 'Unit Traits', 'Detector')],                                                                               [new ImageCard( 0, `${MaterialIcon.Image}`)]),
    new CanopyCellData( 2,   'Anti-Armor Pod',      '',   '',   [new CanopyCell( 0, 'Unit Traits', 'Burrow, Suicide, Pathable')],                                                              [new ImageCard( 0, `${MaterialIcon.Image}`)]),
    new CanopyCellData( 3,   'Assault Troopers',    '',   '',   [new CanopyCell( 0, 'Unit Traits', 'Scout')],                                                                                  [new ImageCard( 0, `${MaterialIcon.Image}`)]),
    new CanopyCellData( 4,   'Mortar Men',          '',   '',   [new CanopyCell( 0, 'Unit Traits', '')],                                                                                       [new ImageCard( 0, `${MaterialIcon.Image}`)]),
    new CanopyCellData( 5,   'Decon ATV',           '',   '',   [], []),
    new CanopyCellData( 6,   'Crusader ATV',        '',   '',   [], []),
    new CanopyCellData( 7,   'Shepard Tank',        '',   '',   [], []),
    new CanopyCellData( 8,   'SAM Tank',            '',   '',   [], []),
    new CanopyCellData( 9,   'Spitfire Chopper',    '',   '',   [], []),
    new CanopyCellData(10,   'Seraphim',            '',   '',   [], []),
    new CanopyCellData(11,   'Ghosts',              '',   '',   [], []),
    new CanopyCellData(12,   'Brimstone Artillery', '',   '',   [], []),
    new CanopyCellData(13,   'Enabler',             '',   '',   [], []),
    new CanopyCellData(14,   'Pulsar Tower',        '',   '',   [], []),
    new CanopyCellData(15,   'Anti-Air Platform',   '',   '',   [], []),
    new CanopyCellData(16,   'Sentinel',            '',   '',   [], []),
    new CanopyCellData(17,   'Sentry Bots',         '',   '',   [], []),
    new CanopyCellData(18,   'Wheel Drones',        '',   '',   [], []),
    new CanopyCellData(19,   'Keeper Tank',         '',   '',   [], []),
    new CanopyCellData(20,   'Pulsar Tank',         '',   '',   [], []),
    new CanopyCellData(21,   'Synergizer',          '',   '',   [], []),
    new CanopyCellData(22,   'Strafer Jet',         '',   '',   [], []),
    new CanopyCellData(23,   'Amplifier',           '',   '',   [], []),
    new CanopyCellData(24,   'Hunter Probe',        '',   '',   [], []),
    new CanopyCellData(25,   'Pulsar Cruiser',      '',   '',   [], []),
    new CanopyCellData(26,   'Heavy Destroyer',     '',   '',   [], []),
    new CanopyCellData(27,   'Phage',               '',   '',   [], []),
    new CanopyCellData(28,   'Tendril Pod',         '',   '',   [], []),
    new CanopyCellData(29,   'Reaper Spine',        '',   '',   [], []),
    new CanopyCellData(30,   'Swarmenvash',         '',   '',   [], []),
    new CanopyCellData(31,   'Scraper',             '',   '',   [], []),
    new CanopyCellData(32,   'Tormenvash',          '',   '',   [], []),
    new CanopyCellData(33,   'Glutton',             '',   '',   [], []),
    new CanopyCellData(34,   'Necrovash',           '',   '',   [], []),
    new CanopyCellData(35,   'Harbinger',           '',   '',   [], []),
    new CanopyCellData(36,   'Screachers',          '',   '',   [], []),
    new CanopyCellData(37,   'Blight Spitter',      '',   '',   [], []),
    new CanopyCellData(38,   'Spawn Pit',           '',   '',   [], []),
    new CanopyCellData(39,   'Nestlings',           '',   '',   [], []),
    new CanopyCellData(40,   'Slayer',              '',   '',   [], []),
    new CanopyCellData(41,   'Swarm Queen',         '',   '',   [], []),
    new CanopyCellData(42,   'Shadow Hive',         '',   '',   [], []),
    new CanopyCellData(43,   'Hiveling',            '',   '',   [], []),
    new CanopyCellData(44,   'Titanipede',          '',   '',   [], []),
  ];
}